---
title: "**Sobre el grupo**"
subtitle: " "
author: "dgonzalez"
date: ""
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    code_folding: hide
    theme: flatly
    css: style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = NA)

# colores
c0= "#FFCC00"
c1= "#FFAD42"
c2= "#FF5A42"
c3= "#E1286F"
c4= "#4983F6"
c5= "#783AC7"
c6= "#2C5697" # AZZUL INSTITUCIONAL
c7= "#F7F7F7" # FONDO GRIS CLARO WEB

# Crear el data.frame
data <- data.frame(
  Nombre = c("OSMEL ALONSO SANCHEZ", "JUAN DIEGO AYALA ARCILA", "MOSQUERA CAICEDO", "JUAN CANCHALA JIMENEZ", "SIMON CARVAJAL CAMPO", "PERDOMO CASTAÑEDA", "ISABELLA CELIS RAMIREZ", "ALEJANDRA CORAL DUQUE", "JUAN DIAZ BENAVIDES", "MARIA GOMEZ PARAMO","CABRERA HERNANDEZ", "ERIC HOLZINGER MEDINA", "DANIELA LASSO GOMEZ", "LONDOÑO MARTINEZ", "JUAN MARULANDA POVEDA", "GUERRERO MONSALVE", "JUAN JOSE MURCIA DAZA", "CARLOS OGONAGA GARCIA", "ALEJANDRA OSPINA GARCIA", "AMY SOFIA PARRA MEJIA", "CATALINA PULIDO RUBIANO", "ANNE RINCON BARRIOS", "LAURA RIVERA TOCORA", "NAOMI RUIZ CEBALLOS", "ISABELA SANABRIA CHACON", "MOHAMAD SHAYEB SHAYEB", "JUAN TORRES MURILLO", "VALENCIA GONZALEZ", "MARIA VERANO RODRIGUEZ", "JUAN VILLARROEL LUENGAS"),
  Emplid = c(8983424, 8958212, 8956230, 8983809, 8957963, 8970458, 8972408, 8979208, 8983956, 8950126, 8982983, 8974713, 8976061, 8968097, 8985198, 8978159, 8952652, 8973603, 8975754, 8975291, 8973988, 8971958, 8977553, 8980848, 8983822, 8963003, 8971204, 8979644, 8979991, 8971881),
  Carrera = c("Ingeniería Civil", "Ingeniería Civil", "Biología", "Ingeniería de Sistemas", "Ingeniería Civil", "Ingeniería Electrónica", "Biología", "Biología", "Ingeniería Mecánica", "Ingeniería Mecánica", "Biología", "Ingeniería Mecánica", "Ingeniería Biomédica", "Ingeniería Biomédica", "Biología", "Ingeniería Biomédica", "Ingeniería Electrónica", "Ingeniería Biomédica", "Ingeniería Biomédica", "Ingeniería Biomédica", "Ingeniería Biomédica", "Ingeniería de Sistemas", "Ingeniería Biomédica", "Biología", "Biología", "Ingeniería de Sistemas", "Ingeniería Electrónica", "Biología", "Biología", "Ingeniería Electrónica"),
  Matriculada = c(1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
  Cancelada = c(0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Perdida = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Promedio = c(4.24, 3.52, 4.15, 3.89, 3.51, 3.69, 3.52, 4.78, 4.48, 3.48, 4.11, 4.32, 3.67, 3.61, 4.2, 4.54, 3.26, 4.21, 4.01, 4.01, 3.9, 3.94, 4.03, 4.08, 4.6, 4.11, 4.04, 4.31, 4.18, 4.32)
)

# Mostrar el data.frame
# print(data)

# Instalar los paquetes necesarios si no están ya instalados
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(dplyr)) install.packages("dplyr")
if (!require(paletteer)) install.packages("paletteer")
library(paletteer)
library(ggplot2)
library(dplyr)

```


<br/><br/>

```{r, echo=FALSE, message=FALSE, warning=FALSE}


# Crear una paleta de colores pastel
# pastel_colors <- c("#FDBFB3", "#FFDDC1", "#FFC8A2", "#FFD8BE", "#FFCB9A", "#FFC3A0", "#FF9AA2", "#FFDAC1")
# pastel_colors <-c("#d2fbff", "#b7dbe6", "#9cbcce", "#819eb6", "#68819e", "#4e6587", "#354b71", "#19325b")

pastel_colors <-  paletteer_c("ggthemes::Orange-Blue-White Diverging", 8)

# Diagrama circular para la variable Carrera
carrera_counts <- data %>% 
  group_by(Carrera) %>% 
  summarise(count = n())

ggplot(carrera_counts, aes(x = "", y = count, fill = Carrera)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_manual(values = pastel_colors) +
  labs(title = "Distribución de Carrera")

# Diagrama de cajas para la variable Promedio
ggplot(data, aes(x = Carrera, y = Promedio, fill = Carrera)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_manual(values = pastel_colors) +
  labs(title = "Diagrama de Cajas para la Variable Promedio por Carrera")



```
```{r}
non =data.frame(id<- 1:30,
           data$Nombre)

non
```

