---
title: "Untitled"
author: "Daniel Gonzalez"
date: "2024-09-23"
output: 
  html_document:
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(r2d3)
```

## Caja Estilizada

Este es un ejemplo de cómo usar el estilo de la caja definido en el archivo CSS:

<div class="box20 with-label">
  <div class="label">Producción ($ MM)</div> <!-- La etiqueta posicionada -->
  <div class="number">234,06</div> <!-- El número grande -->
  <p>Aumento de la producción en los sectores de la economía del territorio<p> <!-- Descripción -->
</div>


<div class="box20 with-label">
  <div class="label">Empleo (#)</div> <!-- La etiqueta posicionada -->
  <div class="number">1.448</div> <!-- El número grande -->
  <p>Aumento del número de ocupados (personas >15 años que trabajaron por lo menos una hora remunerada) en los sectores de la economía del territorio <p> <!-- Descripción -->
</div>


<div class="box20 with-label">
  <div class="label">% PIB Economía del territorio</div> <!-- La etiqueta posicionada -->
  <div class="number">0,153 %</div> <!-- El número grande -->
  <p>% que representa el incremento en la producción sobre el PIB de la economía del territorio<p> <!-- Descripción -->
</div>


<div class="box20 with-label">
  <div class="label">% Empleo Total en la Economía del territorio</div> <!-- La etiqueta posicionada -->
  <div class="number">0,072 %</div> <!-- El número grande -->
  <p>% que representa el incremento en el número de ocupados sobre el total de ocupados de la economía del territorio<p> <!-- Descripción -->
</div>





# Cajas juntas

## Cajas Estilizadas con Paleta de Colores

<div class="container">
<div class="box22">
<h3>**Producción ($ MM)**</h3>
<div class="number">234,06</div>
<p>Aumento de la producción en los sectores de la economía del territorio.</p>
</div>
<div class="box22">
<h3>**% PIB Economía del Territorio**</h3>
<div class="number">0,153 %</div>
<p>% que representa el incremento en la producción sobre el PIB del territorio.</p>
</div>
<div class="box22">
<h3>**Empleo (#)**</h3>
<div class="number">1.448</div>
<p>Aumento del número de ocupados en los sectores de la economía del territorio.</p>
</div>
<div class="box22">
<h3>**% Empleo Total en la Economía del Territorio**</h3>
<div class="number">0,072 %</div>
<p>% que representa el incremento en el número de ocupados sobre el total de ocupados del territorio.</p>
</div>
</div>



